/**
 * The note every new account starts with.
 *
 * S2-18 — the illustration used to be a base64 `data:` URI inlined directly
 * into this string, so a copy of the image bytes was written into every user's
 * welcome note document. It is now a static asset served from `public/`,
 * which keeps the documents small and lets the image be cached at the edge.
 *
 * S2-19 — the "Go to the sky" link pointed at `/notes/create-new`, which is
 * not a route. The route is `/note/create-new`, and it belongs to the
 * frontend rather than the API, so it is built from the frontend's origin.
 */
export const welcomeNote = (baseUrl: string, frontendUrl: string): string => {
  return `<p><strong><span style="font-size: 2.2rem; line-height: 4.4rem">Welcome to Aide-mémoire 📓</span></strong></p><p><strong><span style="font-size: 1rem; line-height: 2rem">Your world awaits you, populate it however you wish</span></strong></p><p></p><p>Thanks for choosing us, we hope you enjoy your stay here with us. Here's a list of things you can do in this application:</p><ol><li><p>Create Notes ➕</p></li><li><p>Edit Notes 🖊</p></li><li><p>Categorize Notes in Sections 📕</p></li><li><p>Give Notes Tags for Grouping and SEO ⚡</p></li><li><p>Search for Notes 🔎</p></li><li><p>Make Notes Public</p></li><li><p>Add a Biography</p></li><li><p>Create Default Note Settings</p></li><li><p>Delete Notes and Sections</p></li><li><p>And Lots More...</p></li></ol><p></p><p>Here are also some of the things you can write in a note:</p><ul><li><p>Various Font and Sizes</p></li></ul><p><span style="font-size: 1.2rem; font-family: Impact, Haettenschweiler, Arial Narrow Bold, sans-serif; line-height: 2.4rem">Hello There</span></p><ul><li><p>Emoji Tab</p></li></ul><p>🥰😜🤪😝</p><ul><li><p>Colored Background</p></li></ul><p><span style="background-color: rgb(26, 244, 41)">Hello There</span></p><ul><li><p>Linked Text</p></li></ul><p><a target="_blank" rel="noopener noreferrer nofollow" href="${frontendUrl}/note/create-new">Go to the sky</a></p><ul><li><p>Images</p><img src="${baseUrl}/img/welcome-note.jpg" alt="inserted image"><p></p></li><li><p><strong><span style="font-size: 1.4rem; line-height: 2.8rem">Bold</span></strong><span style="font-size: 1.4rem; line-height: 2.8rem">, </span><em><span style="font-size: 1.4rem; line-height: 2.8rem">Italics</span></em><span style="font-size: 1.4rem; line-height: 2.8rem">, </span><span style="font-size: 1.4rem; line-height: 2.8rem; text-decoration: underline">Underline</span><span style="font-size: 1.4rem; line-height: 2.8rem"> and </span><s><span style="font-size: 1.4rem; line-height: 2.8rem">Strike through</span></s></p></li><li><p>Code Block</p></li></ul><p><code>const cat = require('cat')</code></p><ul><li><p>Subscript and Superscript</p></li></ul><p>45OC is the temperature of H2O</p><ul><li><p>Some Colored Text</p></li></ul><p><span style="color: rgb(234, 99, 42)">Hello There</span></p><ul><li><p>Block quotes</p></li></ul><blockquote><p>Someone wise once said:</p><p><em>"a stitch in time saves</em></p><p><em>nine"</em></p></blockquote><ul><li><p>And Numbered and Bullet List</p></li></ul><p></p><p>Thanks for taking your time to go through me and as a bonus, if you're ever bored, try hitting these tiny stars floating around. They stop on the first hit and dissapear on the second. </p><p>Good Luck</p>`
}
